### ISSUE TITLE
Implementar condicionais na classe InterfaceUsuario

### ISSUE THREAD

**Issue by Kiamisa** [AnthonyAmaz3d/sistema_financiamento_java#1]
Para o usuário, seria interessante colocar uma validação para valores nulos, assim não ocorre esse tipo de problema. 
![Captura de tela 2024-07-16 161159](https://github.com/user-attachments/assets/7c78ba92-4076-448b-8248-965015e212e8)

**Comment by AnthonyAmaz3d** [comment]
resolvido pai

**Comment by Kiamisa** [comment]
cabra bom rapaz
